# Generated by Django 4.1.7 on 2023-03-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=15, verbose_name='Модель')),
                ('max_weight', models.IntegerField(verbose_name='Грузоподъемность (т)')),
            ],
            options={
                'verbose_name': 'Модель грузовика',
                'verbose_name_plural': 'Модели грузовиков',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('bort_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Бортовой номер')),
                ('current_weight', models.IntegerField(default=0, verbose_name='Текущий груз (т)')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.cargovehicletype')),
            ],
        ),
    ]
