# Generated by Django 4.1.7 on 2023-03-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Автопарк', 'verbose_name_plural': 'Автопарк'},
        ),
    ]
